///CUET_IRON_BAT
#include<bits/stdc++.h>
#define ll long long
#define vll vector<long long>
#define lne '\n'
#define spc ' '
#define fst first
#define sec second
#define inout ios_base::sync_with_stdio(false); cin.tie(0); cout.tie(0);
#define fileopen system("input.txt"); freopen("input.txt","r",stdin); FILE *f=freopen("output.txt","w",stdout);
#define fileclose fclose(f); system("output.txt");
using namespace std;
int main()
{
//    inout
//    fileopen
    for(ll i=1000; i>=1; i-=5)
        cout<<i<<'\t'<<i-1<<'\t'<<i-2<<'\t'<<i-3<<'\t'<<i-4<<lne;
//    fileclose
    return 0;
}

